# vlines (optional), hlines (optional)
button 1:
  x: 45
  y: 187
  vlines:
    baselines:
    - 0
    - 150
    thicknesses:
    - 20
    - 20
  hlines:
    baselines:
    - 0
    thicknesses:
    - 20
button 2:
  x: 137
  y: 186
  vlines:
    baselines: []
    thicknesses: []
  hlines:
    baselines:
    - 32
    thicknesses:
    - 20
button 3:
  x: 209
  y: 51
  vlines:
    baselines:
    - 0
    - 133
    thicknesses:
    - 20
    - 20
  hlines:
    baselines: []
    thicknesses: []
button 4:
  x: 308
  y: 50
  vlines:
    baselines:
    - 0
    - 133
    thicknesses:
    - 20
    - 20
  hlines:
    baselines: []
    thicknesses: []
button 5:
  x: 402
  y: 51
  vlines:
    baselines:
    - 0
    - 133
    thicknesses:
    - 20
    - 20
  hlines:
    baselines: []
    thicknesses: []
button 6:
  x: 208
  y: 350
  vlines:
    baselines:
    - 277
    - 407
    thicknesses:
    - 20
    - 20
  hlines:
    baselines: []
    thicknesses: []
button 7:
  x: 302
  y: 349
  vlines:
    baselines:
    - 277
    - 407
    thicknesses:
    - 20
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 8:
  x: 402
  y: 347
  vlines:
    baselines:
    - 277
    - 407
    thicknesses:
    - 20
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 9:
  x: 490
  y: 171
  vlines:
    baselines:
    - 133
    - 214
    thicknesses:
    - 20
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 10:
  x: 490
  y: 232
  vlines:
    baselines:
    - 277
    - 214
    thicknesses:
    - 20
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 11:
  x: 602
  y: 93
  vlines:
    baselines:
    - 214
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 12:
  x: 704
  y: 93
  vlines:
    baselines:
    - 214
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 13:
  x: 808
  y: 96
  vlines:
    baselines:
    - 214
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 14:
  x: 880
  y: 224
  vlines:
    baselines:
    - 214
    - 284
    thicknesses:
    - 20
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 15:
  x: 639
  y: 411
  vlines:
    baselines:
    - 284
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 16:
  x: 719
  y: 410
  vlines:
    baselines:
    - 284
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 17:
  x: 799
  y: 410
  vlines:
    baselines:
    - 284
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 18:
  x: 880
  y: 410
  vlines:
    baselines:
    - 284
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 19:
  x: 952
  y: 410
  vlines:
    baselines:
    - 284
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 20:
  x: 1028
  y: 410
  vlines:
    baselines:
    - 284
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
button 21:
  x: 1105
  y: 410
  vlines:
    baselines:
    - 284
    thicknesses:
    - 20
  hlines:
    baselines: null
    thicknesses: null
