Buttons:
  button 1:
    x: 32
    y: 195
    hlines:
      lengths:
      - -45
      - 70
      thicknesses:
      - 20
      - 20
  button 2:
    x: 125
    y: 195
    hlines:
      lengths:
      - -105
      - 70
      thicknesses:
      - 20
      - 20
  button 3:
    x: 229
    y: 47
    vlines:
      lengths:
      - -51
      - 60
      thicknesses:
      - 20
      - 20
  button 4:
    x: 317
    y: 48
    vlines:
      lengths:
      - -50
      - 60
      thicknesses:
      - 20
      - 20
  button 5:
    x: 409
    y: 49
    vlines:
      lengths:
      - -50
      - 60
      thicknesses:
      - 20
      - 20
  button 6:
    x: 222
    y: 344
    vlines:
      lengths:
      - -60
      - 57
      thicknesses:
      - 20
      - 20
  button 7:
    x: 310
    y: 344
    vlines:
      lengths:
      - -60
      - 57
      thicknesses:
      - 20
      - 20
  button 8:
    x: 401
    y: 344
    vlines:
      lengths:
      - -60
      - 57
      thicknesses:
      - 20
      - 20
  button 9:
    x: 480
    y: 157
    vlines:
      lengths:
      - -50
      - 43
      thicknesses:
      - 20
      - 20
  button 10:
    x: 480
    y: 237
    vlines:
      lengths:
      - -50
      - 55
      thicknesses:
      - 20
      - 20
  button 11:
    x: 594
    y: 85
    vlines:
      lengths:
      - 111
      thicknesses:
      - 20
  button 12:
    x: 696
    y: 85
    vlines:
      lengths:
      - 111
      thicknesses:
      - 20
  button 13:
    x: 800
    y: 88
    vlines:
      lengths:
      - 111
      thicknesses:
      - 20
  button 14:
    x: 870
    y: 238
    vlines:
      lengths:
      - -35
      - 60
      thicknesses:
      - 20
      - 20
  button 15:
    x: 631
    y: 402
    vlines:
      lengths:
      - -126
      thicknesses:
      - 20
  button 16:
    x: 711
    y: 402
    vlines:
      lengths:
      - -126
      thicknesses:
      - 20
  button 17:
    x: 791
    y: 402
    vlines:
      lengths:
      - -126
      thicknesses:
      - 20
  button 18:
    x: 871
    y: 403
    vlines:
      lengths:
      - -126
      thicknesses:
      - 20
  button 19:
    x: 944
    y: 402
    vlines:
      lengths:
      - -126
      thicknesses:
      - 20
  button 20:
    x: 1020
    y: 402
    vlines:
      lengths:
      - -126
      thicknesses:
      - 20
  button 21:
    x: 1097
    y: 402
    vlines:
      lengths:
      - -126
      thicknesses:
      - 20
Lines:
  vlines:
    starts:
      x:
      - 186
      y:
      - 100
    lengths:
    - 200
    thicknesses:
    - 20
  hlines:
    starts:
      x:
      - 192
      - 192
      - 471
      - 632
      y:
      - 100
      - 280
      - 185
      - 276
    lengths:
    - 300
    - 300
    - 410
    - 476
    thicknesses:
    - 20
    - 20
    - 20
    - 20
