# This file sets the sensor channels we want to display on the main page of the live data streaming window. 
# They must match the sensors and channels set in data_saving.yaml
#
# Just comment out the lines you don't want displayed on the main page!
---
Dummy Sensor:
  Dummy sensor data 1 (mm):