# This file holds the entries we want in the logging panel of the GUI. It's set up as a dictionary
# in case we need to pass in additional information per entry (default value, cap the answer at X chars, etc)
# but currently all we use are the keys
---
Logs:
  Core Length (units):
  Core ID:
  Timestamp (HH:MM:SS):
  Notes:
New project:
  User metadata: ["Cut Date", "Cut By", "Measured Date", "Measured By"]
  Sample data: ["Flask", "Core", "Top Depth", "Bottom Depth", "Weight 1", "Weight 2", "Remarks"]