# This file sets up configuration parameters for sensor communication, like serial ports, baud rates, and arduino pins
---
Arduino:
  serial port: "COM3"
  baud rate: 19200
Pneumatic valves:
  Button 1:
    digital pin: 2
  Button 2:
    digital pin: 3
  Button 3:
    digital pin: 4
  Button 4:
    digital pin: 5
  Button 5:
    digital pin: 6
  Button 6:
    digital pin: 7
  Button 7:
    digital pin: 8
  Button 8:
    digital pin: 9
  Button 9:
    digital pin: 10
  Button 10:
    digital pin: 11
  Button 11:
    digital pin: 12
  Button 12:
    digital pin: 13
  Button 13:
    digital pin: 14
  Button 14:
    digital pin: 15
  Button 15:
    digital pin: 16
  Button 16:
    digital pin: 17
  Button 17:
    digital pin: 18
  Button 18:
    digital pin: 19
  Button 19:
    digital pin: 20
  Button 20:
    digital pin: 21
  Button 21:
    digital pin: 22

